# Generated by Django 2.1.7 on 2019-06-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_landlordform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordform',
            name='re_password',
        ),
        migrations.RemoveField(
            model_name='renterform',
            name='re_password',
        ),
    ]
